### ISSUE TITLE
The artifact uploaded in one job is not located in another one

### ISSUE THREAD

**Issue by Sevastian-Bahynskyi** [Sevastian-Bahynskyi/squared-layout#7]
In `build-and-release` job the ./dist is uploaded as an artifact and downloaded in `deploy` job. However neither ./dist nor `build-artifact.zip` is found, therefore the `deploy` job is failed.

```yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Release and publish package
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./dist

  deploy:
    needs: build-and-publish
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: gh-pages
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Extract build artifact
        run: |
          mkdir -p ./dist
          unzip -o build-artifact.zip -d ./dist

      - name: List ./dist directory
        run: ls -R ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

```
